############################################################################
# 原則 http://jekyllrb.com/docs/configuration/#default-configuration からの
# 差分のみ記述している。記述順序も前述に従う。

### Handling Reading
exclude:
  - 'scripts'
  - 'Gemfile'
  - 'LICENSE.txt'
  - 'README.md'
  - 'vendor'
  - 'slacklog_template'
  - 'Makefile'
  - 'slacklog_data'
  - 'tmp'

# デフォルトと同じだが「utf-8で記事を書こう」という宣言的な意味合で残した。
encoding: utf-8

### Plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

### Markdown Processors
kramdown:
  input: GFM
